@echo off
chcp 65001 >nul
cd /d c:\cscode\Samutprakan_Travelweb
echo Deleting old database...
del prisma\dev.db 2>nul
echo Running Prisma push...
call npx prisma db push 2>&1
echo Running seed...
call node prisma/seed.js 2>&1
echo Done! Starting server...
node server/index.js
